In [97]:
import re
# import tweepy
import pandas as pd
import datetime 
from sqlalchemy import create_engine
# from sshtunnel import SSHTunnelForwarder
import configparser
import psycopg2
cfg = configparser.RawConfigParser()
cfg.read('/home/carpiero/ir/pass_projects/pass.ini')

['/home/carpiero/ir/pass_projects/pass.ini']

In [2]:
user=cfg['ssh']['username']
passw=cfg['ssh']['password']

engine = create_engine(f'postgresql://{user}:{passw}@asuscar.duckdns.org/carpiero', echo=True)

# engine = create_engine(f'postgresql://{user}:{passw}@192.168.1.170/carpiero', echo=True)

In [3]:

# df_postgresql = pd.read_sql_query("SELECT * FROM twitter_operators", engine, coerce_float=True, parse_dates=['created_at'])


df_postgresql = pd.read_sql_query("SELECT * FROM twitter_operators", engine, coerce_float=True, parse_dates=['created_at'])



df_postgresql.info(memory_usage='deep')

2020-12-14 17:44:08,254 INFO sqlalchemy.engine.base.Engine select version()
2020-12-14 17:44:08,255 INFO sqlalchemy.engine.base.Engine {}
2020-12-14 17:44:08,277 INFO sqlalchemy.engine.base.Engine select current_schema()
2020-12-14 17:44:08,278 INFO sqlalchemy.engine.base.Engine {}
2020-12-14 17:44:08,295 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-12-14 17:44:08,296 INFO sqlalchemy.engine.base.Engine {}
2020-12-14 17:44:08,306 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-12-14 17:44:08,311 INFO sqlalchemy.engine.base.Engine {}
2020-12-14 17:44:08,322 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2020-12-14 17:44:08,324 INFO sqlalchemy.engine.base.Engine {}
2020-12-14 17:44:08,342 INFO sqlalchemy.engine.base.OptionEngine SELECT * FROM twitter_operators
2020-12-14 17:44:08,343 INFO sqlalchemy.engine.base.OptionEngine {}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68071 entries, 0 to 68070
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   created_at                68071 non-null  datetime64[ns]
 1   tweet_id                  68071 non-null  object
 2   Tweet_Content             68071 non-null  object
 3   name                      68071 non-null  object
 4   user_id                   68071 non-null  object
 5   user_followers            68071 non-null  int64
 6   user_location             68071 non-null  object
 7   source                    68071 non-null  object
 8   entities                  68071 non-null  object
 9   reply_user_id             68071 non-null  object
 10  reply_status_id           68071 non-null  object
 11  Tweet_Number_of_Likes     68071 non-null  int64
 12  Tweet_Number_of_Retweets  68071 non-null  int64
 13  username                  68071 non-null  object
 14  GRUPO                     68071 non-null  object
 15  API                       68071 non-null  object
dtypes: datetime64[ns](1), int64(3), object(12)
memory usage: 136.8 MB

In [4]:
from ast import literal_eval


df_postgresql['name'] = df_postgresql['name'].astype('category')
df_postgresql['user_id'] = df_postgresql['user_id'].astype('category')
df_postgresql['user_location'] = df_postgresql['user_location'].astype('category')
df_postgresql['source'] = df_postgresql['source'].astype('category')
df_postgresql['reply_user_id'] = df_postgresql['reply_user_id'].astype('category')
df_postgresql['reply_status_id'] = df_postgresql['reply_status_id'].astype('category')
df_postgresql['username'] = df_postgresql['username'].astype('category')
df_postgresql['GRUPO'] = df_postgresql['GRUPO'].astype('category')
df_postgresql['entities']=df_postgresql['entities'].apply(literal_eval)
df_postgresql=df_postgresql.drop(columns=['API'])



df_postgresql.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68071 entries, 0 to 68070
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   created_at                68071 non-null  datetime64[ns]
 1   tweet_id                  68071 non-null  object
 2   Tweet_Content             68071 non-null  object
 3   name                      68071 non-null  category
 4   user_id                   68071 non-null  category
 5   user_followers            68071 non-null  int64
 6   user_location             68071 non-null  category
 7   source                    68071 non-null  category
 8   entities                  68071 non-null  object
 9   reply_user_id             68071 non-null  category
 10  reply_status_id           68071 non-null  category
 11  Tweet_Number_of_Likes     68071 non-null  int64
 12  Tweet_Number_of_Retweets  68071 non-null  int64
 13  username                  68071 non-null  category
 14  GRUPO                     68071 non-null  category
dtypes: category(8), datetime64[ns](1), int64(3), object(3)
memory usage: 51.8 MB

In [5]:
df_postgresql

,created_at,tweet_id,Tweet_Content,name,user_id,user_followers,user_location,source,entities,reply_user_id,reply_status_id,Tweet_Number_of_Likes,Tweet_Number_of_Retweets,username,GRUPO
0,2020-11-25 23:45:45,1331745922720673793,@vodafone_es Espero que se me envien los termi...,Diejeitor,880183399356542977,1,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",880183399356542977,1331745644848046080,1,0,@vodafone_es,Vodafone
1,2020-11-25 23:44:56,1331745719603097601,@vodafone_es Ten√©is solo unidades para los que...,Diejeitor,880183399356542977,1,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",880183399356542977,1331745644848046080,1,0,@vodafone_es,Vodafone
2,2020-11-25 23:44:39,1331745644848046080,"@vodafone_es Hola Vodafone, aun me deb√©is 2 m...",Diejeitor,880183399356542977,1,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",18939115,no,1,0,@vodafone_es,Vodafone
3,2020-11-25 23:18:47,1331739136802361345,@DobbyFawkes @vodafone_es Yo tampoco veo el mo...,Gata Presumida,2822873697,275,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",490711473,1331716565402783748,2,0,@vodafone_es,Vodafone
4,2020-11-25 23:17:26,1331738799206969346,@vodafone_es Hace 4 meses me cambi√© a Vodafone...,solis jimenez carmen,975955338469040128,4,,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",18939115,no,1,0,@vodafone_es,Vodafone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68066,2020-12-13 10:52:23,1338074281729810433,RT @AnaAgp_1967: @Nosmatanatodos @Lowi_es @App...,Jos√© Manuel G√≥mez,2580024029,631,,Twitter for Android,"{'hashtags': [{'text': 'BoycotLowi', 'indices'...",no,no,0,3,@lowi_es,Vodafone
68067,2020-12-13 10:37:12,1338070460366548995,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Jjsb44üîª,914488859517493249,12320,Galicia,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,124,@lowi_es,Vodafone
68068,2020-12-13 01:13:25,1337928579338940417,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Antonio J. The best,457449143,834,In the world,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,124,@lowi_es,Vodafone
68069,2020-12-13 01:05:05,1337926480790220804,RT @armartinez51: @AnaAgp_1967 @Lowi_es @Apple...,Raquel Fdez-Veiga,2439711755,8502,Barcelona,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,2,@lowi_es,Vodafone
68070,2020-12-13 01:04:52,1337926427530899458,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Raquel Fdez-Veiga,2439711755,8502,Barcelona,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,124,@lowi_es,Vodafone

In [6]:
df_postgresql[['created_at']].resample('D', on='created_at').count()

            created_at
created_at
2020-11-25        4247
2020-11-26        3958
2020-11-27        5230
2020-11-28        2854
2020-11-29        1774
2020-11-30        4119
2020-12-01        3823
2020-12-02        3772
2020-12-03        4341
2020-12-04        3513
2020-12-05        2875
2020-12-06        2421
2020-12-07        3240
2020-12-08        3700
2020-12-09        3791
2020-12-10        4847
2020-12-11        4710
2020-12-12        2893
2020-12-13        1963

In [7]:
###### import pandas_profiling

# df_postgresql.profile_report()a

In [8]:
def hashtags(x):
    return x['hashtags']

def urls(x):
    if len(x['urls'])>0:
        return x['urls'][0]['url']
    else:
        return 'no url'

    
df_postgresql['hashtags']=df_postgresql['entities'].apply(hashtags)
df_postgresql['urls']=df_postgresql['entities'].apply(urls)






df_postgresql.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68071 entries, 0 to 68070
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   created_at                68071 non-null  datetime64[ns]
 1   tweet_id                  68071 non-null  object
 2   Tweet_Content             68071 non-null  object
 3   name                      68071 non-null  category
 4   user_id                   68071 non-null  category
 5   user_followers            68071 non-null  int64
 6   user_location             68071 non-null  category
 7   source                    68071 non-null  category
 8   entities                  68071 non-null  object
 9   reply_user_id             68071 non-null  category
 10  reply_status_id           68071 non-null  category
 11  Tweet_Number_of_Likes     68071 non-null  int64
 12  Tweet_Number_of_Retweets  68071 non-null  int64
 13  username                  68071 non-null  category
 14  GRUPO                     68071 non-null  category
 15  hashtags                  68071 non-null  object
 16  urls                      68071 non-null  object
dtypes: category(8), datetime64[ns](1), int64(3), object(5)
memory usage: 59.9 MB

In [9]:
df_postgresql['username'].value_counts()

@vodafone_es    24818
@orange_es      10661
@movistar_es    10382
@yoigo           8679
@vodafoneyu      3691
@masmovil        3087
@pepephone       2245
@lowi_es         1588
@o2es            1435
@Amena            938
@simyo_es         451
@TuentiES          60
@jazztel           36
Name: username, dtype: int64

In [10]:
from transformers import pipeline

print(pipeline('sentiment-analysis')('we love you'))

/home/carpiero/miniconda3/envs/sentiment_env/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0

[{'label': 'POSITIVE', 'score': 0.9998704791069031}]

In [11]:
classifier = pipeline('sentiment-analysis', model='nlptown/bert-base-multilingual-uncased-sentiment')

In [12]:
classifier('muy malo')

[{'label': '1 star', 'score': 0.8717141151428223}]

In [101]:

list_tweet=list(df_postgresql['Tweet_Content'])

cl=list_tweet

len(cl)

68071

In [102]:

jump=2000
cla=[classifier(cl[x:x+jump]) for x in range(0,len(cl),jump)]
cla=[y for x in cla for y in x]

    
len(cla)

68071

In [103]:
def rem_stars(x):
    m=re.sub('stars|star','',x)
    return int(m)

In [104]:
cl_label=[rem_stars(x.get('label')) for x in cla]
cl_score=[x.get('score') for x in cla]



len(cl_label)

68071

In [105]:
df_postgresql['stars'] = pd.Series((cl_label), index=df_postgresql.index)
df_postgresql['stars_score'] = pd.Series((cl_score), index=df_postgresql.index)

In [106]:
df_postgresql['stars'].value_counts()

1    43968
5    20011
3     2615
4      889
2      588
Name: stars, dtype: int64

In [107]:
df_postgresql['stars_score'].describe()

count    68071.000000
mean         0.469400
std          0.167506
min          0.208895
25%          0.325672
50%          0.440438
75%          0.600124
max          0.976332
Name: stars_score, dtype: float64

In [109]:
df_postgresql.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68071 entries, 0 to 68070
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   created_at                68071 non-null  datetime64[ns]
 1   tweet_id                  68071 non-null  object
 2   Tweet_Content             68071 non-null  object
 3   name                      68071 non-null  category
 4   user_id                   68071 non-null  category
 5   user_followers            68071 non-null  int64
 6   user_location             68071 non-null  category
 7   source                    68071 non-null  category
 8   entities                  68071 non-null  object
 9   reply_user_id             68071 non-null  category
 10  reply_status_id           68071 non-null  category
 11  Tweet_Number_of_Likes     68071 non-null  int64
 12  Tweet_Number_of_Retweets  68071 non-null  int64
 13  username                  68071 non-null  category
 14  GRUPO                     68071 non-null  category
 15  hashtags                  68071 non-null  object
 16  urls                      68071 non-null  object
 17  stars                     68071 non-null  int64
 18  stars_score               68071 non-null  float64
dtypes: category(8), datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 68.3 MB

In [111]:
df_postgresql

,created_at,tweet_id,Tweet_Content,name,user_id,user_followers,user_location,source,entities,reply_user_id,reply_status_id,Tweet_Number_of_Likes,Tweet_Number_of_Retweets,username,GRUPO,hashtags,urls,stars,stars_score
0,2020-11-25 23:45:45,1331745922720673793,@vodafone_es Espero que se me envien los termi...,Diejeitor,880183399356542977,1,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",880183399356542977,1331745644848046080,1,0,@vodafone_es,Vodafone,[],no url,1,0.403197
1,2020-11-25 23:44:56,1331745719603097601,@vodafone_es Ten√©is solo unidades para los que...,Diejeitor,880183399356542977,1,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",880183399356542977,1331745644848046080,1,0,@vodafone_es,Vodafone,[],no url,1,0.445512
2,2020-11-25 23:44:39,1331745644848046080,"@vodafone_es Hola Vodafone, aun me deb√©is 2 m...",Diejeitor,880183399356542977,1,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",18939115,no,1,0,@vodafone_es,Vodafone,[],https://t.co/T6RnbDdURU,1,0.328059
3,2020-11-25 23:18:47,1331739136802361345,@DobbyFawkes @vodafone_es Yo tampoco veo el mo...,Gata Presumida,2822873697,275,,Twitter Web App,"{'hashtags': [], 'symbols': [], 'user_mentions...",490711473,1331716565402783748,2,0,@vodafone_es,Vodafone,[],no url,1,0.444034
4,2020-11-25 23:17:26,1331738799206969346,@vodafone_es Hace 4 meses me cambi√© a Vodafone...,solis jimenez carmen,975955338469040128,4,,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",18939115,no,1,0,@vodafone_es,Vodafone,[],https://t.co/WJdmBBMHCZ,1,0.505059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68066,2020-12-13 10:52:23,1338074281729810433,RT @AnaAgp_1967: @Nosmatanatodos @Lowi_es @App...,Jos√© Manuel G√≥mez,2580024029,631,,Twitter for Android,"{'hashtags': [{'text': 'BoycotLowi', 'indices'...",no,no,0,3,@lowi_es,Vodafone,"[{'text': 'BoycotLowi', 'indices': [103, 114]}...",no url,1,0.733965
68067,2020-12-13 10:37:12,1338070460366548995,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Jjsb44üîª,914488859517493249,12320,Galicia,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,124,@lowi_es,Vodafone,[],no url,1,0.654803
68068,2020-12-13 01:13:25,1337928579338940417,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Antonio J. The best,457449143,834,In the world,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,124,@lowi_es,Vodafone,[],no url,1,0.654803
68069,2020-12-13 01:05:05,1337926480790220804,RT @armartinez51: @AnaAgp_1967 @Lowi_es @Apple...,Raquel Fdez-Veiga,2439711755,8502,Barcelona,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,2,@lowi_es,Vodafone,[],no url,3,0.321390
68070,2020-12-13 01:04:52,1337926427530899458,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Raquel Fdez-Veiga,2439711755,8502,Barcelona,Twitter for Android,"{'hashtags': [], 'symbols': [], 'user_mentions...",no,no,0,124,@lowi_es,Vodafone,[],no url,1,0.654803

In [122]:
df_postgresql['entities']=df_postgresql['entities'].apply(literal_eval)

In [120]:
import json

df_postgresql['entities'] = df_postgresql['entities'].apply(json.dumps)
df_postgresql['hashtags'] = df_postgresql['hashtags'].apply(json.dumps)

In [124]:
df_postgresql=df_postgresql.drop(columns=['hashtags'])

In [125]:
df_postgresql

,created_at,tweet_id,Tweet_Content,name,user_id,user_followers,user_location,source,entities,reply_user_id,reply_status_id,Tweet_Number_of_Likes,Tweet_Number_of_Retweets,username,GRUPO,urls,stars,stars_score
0,2020-11-25 23:45:45,1331745922720673793,@vodafone_es Espero que se me envien los termi...,Diejeitor,880183399356542977,1,,Twitter Web App,"""{'hashtags': [], 'symbols': [], 'user_mention...",880183399356542977,1331745644848046080,1,0,@vodafone_es,Vodafone,no url,1,0.403197
1,2020-11-25 23:44:56,1331745719603097601,@vodafone_es Ten√©is solo unidades para los que...,Diejeitor,880183399356542977,1,,Twitter Web App,"""{'hashtags': [], 'symbols': [], 'user_mention...",880183399356542977,1331745644848046080,1,0,@vodafone_es,Vodafone,no url,1,0.445512
2,2020-11-25 23:44:39,1331745644848046080,"@vodafone_es Hola Vodafone, aun me deb√©is 2 m...",Diejeitor,880183399356542977,1,,Twitter Web App,"""{'hashtags': [], 'symbols': [], 'user_mention...",18939115,no,1,0,@vodafone_es,Vodafone,https://t.co/T6RnbDdURU,1,0.328059
3,2020-11-25 23:18:47,1331739136802361345,@DobbyFawkes @vodafone_es Yo tampoco veo el mo...,Gata Presumida,2822873697,275,,Twitter Web App,"""{'hashtags': [], 'symbols': [], 'user_mention...",490711473,1331716565402783748,2,0,@vodafone_es,Vodafone,no url,1,0.444034
4,2020-11-25 23:17:26,1331738799206969346,@vodafone_es Hace 4 meses me cambi√© a Vodafone...,solis jimenez carmen,975955338469040128,4,,Twitter for Android,"""{'hashtags': [], 'symbols': [], 'user_mention...",18939115,no,1,0,@vodafone_es,Vodafone,https://t.co/WJdmBBMHCZ,1,0.505059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68066,2020-12-13 10:52:23,1338074281729810433,RT @AnaAgp_1967: @Nosmatanatodos @Lowi_es @App...,Jos√© Manuel G√≥mez,2580024029,631,,Twitter for Android,"""{'hashtags': [{'text': 'BoycotLowi', 'indices...",no,no,0,3,@lowi_es,Vodafone,no url,1,0.733965
68067,2020-12-13 10:37:12,1338070460366548995,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Jjsb44üîª,914488859517493249,12320,Galicia,Twitter for Android,"""{'hashtags': [], 'symbols': [], 'user_mention...",no,no,0,124,@lowi_es,Vodafone,no url,1,0.654803
68068,2020-12-13 01:13:25,1337928579338940417,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Antonio J. The best,457449143,834,In the world,Twitter for Android,"""{'hashtags': [], 'symbols': [], 'user_mention...",no,no,0,124,@lowi_es,Vodafone,no url,1,0.654803
68069,2020-12-13 01:05:05,1337926480790220804,RT @armartinez51: @AnaAgp_1967 @Lowi_es @Apple...,Raquel Fdez-Veiga,2439711755,8502,Barcelona,Twitter for Android,"""{'hashtags': [], 'symbols': [], 'user_mention...",no,no,0,2,@lowi_es,Vodafone,no url,3,0.321390
68070,2020-12-13 01:04:52,1337926427530899458,RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d ...,Raquel Fdez-Veiga,2439711755,8502,Barcelona,Twitter for Android,"""{'hashtags': [], 'symbols': [], 'user_mention...",no,no,0,124,@lowi_es,Vodafone,no url,1,0.654803

In [128]:
user = cfg['ssh']['username']
passw = cfg['ssh']['password']
engine = create_engine(f'postgresql://{user}:{passw}@asuscar.duckdns.org/carpiero' , echo=True)
postgresql_connection = engine.connect()

postgresql_table = "twitter_operators_sent"
df_postgresql.to_sql(postgresql_table, postgresql_connection, if_exists='append',index=False)

2020-12-15 10:25:08,814 INFO sqlalchemy.engine.base.Engine select version()
2020-12-15 10:25:08,815 INFO sqlalchemy.engine.base.Engine {}
2020-12-15 10:25:08,831 INFO sqlalchemy.engine.base.Engine select current_schema()
2020-12-15 10:25:08,832 INFO sqlalchemy.engine.base.Engine {}
2020-12-15 10:25:08,849 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-12-15 10:25:08,849 INFO sqlalchemy.engine.base.Engine {}
2020-12-15 10:25:08,859 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-12-15 10:25:08,860 INFO sqlalchemy.engine.base.Engine {}
2020-12-15 10:25:08,869 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2020-12-15 10:25:08,870 INFO sqlalchemy.engine.base.Engine {}
2020-12-15 10:25:08,995 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2020-12-15 10:25:08,996 INFO sqlalchemy.engine.base.Engine {'name': 'twitter_operators_sent'}
2020-12-15 10:25:09,244 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-12-15 10:25:12,717 INFO sqlalchemy.engine.base.Engine INSERT INTO twitter_operators_sent (created_at, tweet_id, "Tweet_Content", name, user_id, user_followers, user_location, source, entities, reply_user_id, reply_status_id, "Tweet_Number_of_Likes", "Tweet_Number_of_Retweets", username, "GRUPO", urls, stars, stars_score) VALUES (%(created_at)s, %(tweet_id)s, %(Tweet_Content)s, %(name)s, %(user_id)s, %(user_followers)s, %(user_location)s, %(source)s, %(entities)s, %(reply_user_id)s, %(reply_status_id)s, %(Tweet_Number_of_Likes)s, %(Tweet_Number_of_Retweets)s, %(username)s, %(GRUPO)s, %(urls)s, %(stars)s, %(stars_score)s)
2020-12-15 10:25:12,718 INFO sqlalchemy.engine.base.Engine ({'created_at': datetime.datetime(2020, 11, 25, 23, 45, 45), 'tweet_id': '1331745922720673793', 'Tweet_Content': '@vodafone_es Espero que se me envien los terminales antes de pasar por la via procesal...', 'name': 'Diejeitor', 'user_id': '880183399356542977', 'user_followers': 1, 'user_location': '', 'source': 'Twitter Web App', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \'id_str\': \'18939115\', \'indices\': [0, 12]}], \'urls\': []}"', 'reply_user_id': '880183399356542977', 'reply_status_id': '1331745644848046080', 'Tweet_Number_of_Likes': 1, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.40319666266441345}, {'created_at': datetime.datetime(2020, 11, 25, 23, 44, 56), 'tweet_id': '1331745719603097601', 'Tweet_Content': '@vodafone_es Ten√©is solo unidades para los que los pagan mas caros?', 'name': 'Diejeitor', 'user_id': '880183399356542977', 'user_followers': 1, 'user_location': '', 'source': 'Twitter Web App', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \'id_str\': \'18939115\', \'indices\': [0, 12]}], \'urls\': []}"', 'reply_user_id': '880183399356542977', 'reply_status_id': '1331745644848046080', 'Tweet_Number_of_Likes': 1, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.44551166892051697}, {'created_at': datetime.datetime(2020, 11, 25, 23, 44, 39), 'tweet_id': '1331745644848046080', 'Tweet_Content': '@vodafone_es  Hola Vodafone, aun me deb√©is 2 moviles que me hab√≠ais ofrecido por una oferta de retenci√≥n, llam√© hoy‚Ä¶ https://t.co/T6RnbDdURU', 'name': 'Diejeitor', 'user_id': '880183399356542977', 'user_followers': 1, 'user_location': '', 'source': 'Twitter Web App', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \' ... (108 characters truncated) ... _url\': \'https://twitter.com/i/web/status/1331745644848046080\', \'display_url\': \'twitter.com/i/web/status/1\\u2026\', \'indices\': [117, 140]}]}"', 'reply_user_id': '18939115', 'reply_status_id': 'no', 'Tweet_Number_of_Likes': 1, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'https://t.co/T6RnbDdURU', 'stars': 1, 'stars_score': 0.3280593156814575}, {'created_at': datetime.datetime(2020, 11, 25, 23, 18, 47), 'tweet_id': '1331739136802361345', 'Tweet_Content': '@DobbyFawkes @vodafone_es Yo tampoco veo el momento de irme de vodafone üò¢', 'name': 'Gata Presumida', 'user_id': '2822873697', 'user_followers': 275, 'user_location': '', 'source': 'Twitter Web App', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'DobbyFawkes\', \'name\': \'DobbyFawkes\', \'id\': 490711473, \'id_str\': ... (45 characters truncated) ... een_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \'id_str\': \'18939115\', \'indices\': [13, 25]}], \'urls\': []}"', 'reply_user_id': '490711473', 'reply_status_id': '1331716565402783748', 'Tweet_Number_of_Likes': 2, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.4440343976020813}, {'created_at': datetime.datetime(2020, 11, 25, 23, 17, 26), 'tweet_id': '1331738799206969346', 'Tweet_Content': '@vodafone_es Hace 4 meses me cambi√© a Vodafone y no paro de tener cortes, no puedo ver ni los story de Instagram, l‚Ä¶ https://t.co/WJdmBBMHCZ', 'name': 'solis jimenez carmen', 'user_id': '975955338469040128', 'user_followers': 4, 'user_location': '', 'source': 'Twitter for Android', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \' ... (108 characters truncated) ... _url\': \'https://twitter.com/i/web/status/1331738799206969346\', \'display_url\': \'twitter.com/i/web/status/1\\u2026\', \'indices\': [117, 140]}]}"', 'reply_user_id': '18939115', 'reply_status_id': 'no', 'Tweet_Number_of_Likes': 1, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'https://t.co/WJdmBBMHCZ', 'stars': 1, 'stars_score': 0.505058765411377}, {'created_at': datetime.datetime(2020, 11, 25, 23, 15, 1), 'tweet_id': '1331738191137792006', 'Tweet_Content': 'RT @mangelpeirats: Abro hilo de c√≥mo @vodafone_es quiere robarme mis macarrones\n+', 'name': 'Mar√≠a', 'user_id': '143130865', 'user_followers': 597, 'user_location': 'Carabanchel', 'source': 'Twitter Web App', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'mangelpeirats\', \'name\': \'mangelpeirats\', \'id\': 124788537661981901 ... (69 characters truncated) ... een_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \'id_str\': \'18939115\', \'indices\': [37, 49]}], \'urls\': []}"', 'reply_user_id': 'no', 'reply_status_id': 'no', 'Tweet_Number_of_Likes': 0, 'Tweet_Number_of_Retweets': 9, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.7833789587020874}, {'created_at': datetime.datetime(2020, 11, 25, 23, 6, 59), 'tweet_id': '1331736167675555848', 'Tweet_Content': '@vodafone_es Alguna soluci√≥n?\nAlguna noticia?\nAlgo?', 'name': 'New Thunderfruit', 'user_id': '303095098', 'user_followers': 94, 'user_location': 'Espa√±a', 'source': 'Twitter for Android', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \'id_str\': \'18939115\', \'indices\': [0, 12]}], \'urls\': []}"', 'reply_user_id': '18939115', 'reply_status_id': '1331563408320319492', 'Tweet_Number_of_Likes': 1, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.31963983178138733}, {'created_at': datetime.datetime(2020, 11, 25, 23, 1, 54), 'tweet_id': '1331734887691407360', 'Tweet_Content': 'Detesto este tlfn dios CUANDO SER√Å QUE ME LLEGARA EL NUEVO????? @vodafone_es detesto.', 'name': 'Augusto B√¶ta', 'user_id': '613992461', 'user_followers': 1069, 'user_location': 'Madrid', 'source': 'Twitter for iPhone', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'vodafone_es\', \'name\': \'Vodafone Espa\\u00f1a\', \'id\': 18939115, \'id_str\': \'18939115\', \'indices\': [64, 76]}], \'urls\': []}"', 'reply_user_id': 'no', 'reply_status_id': 'no', 'Tweet_Number_of_Likes': 1, 'Tweet_Number_of_Retweets': 0, 'username': '@vodafone_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.7509916424751282}  ... displaying 10 of 68071 total bound parameter sets ...  {'created_at': datetime.datetime(2020, 12, 13, 1, 5, 5), 'tweet_id': '1337926480790220804', 'Tweet_Content': 'RT @armartinez51: @AnaAgp_1967 @Lowi_es @Apple Las estafas en peque√±as cantidades pero a muchos es m√°s rentable.', 'name': 'Raquel Fdez-Veiga', 'user_id': '2439711755', 'user_followers': 8502, 'user_location': 'Barcelona', 'source': 'Twitter for Android', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'armartinez51\', \'name\': \'ANTONIO RODRIGUEZ\', \'id\': 754708136, \'id ... (320 characters truncated) ... ': [31, 39]}, {\'screen_name\': \'Apple\', \'name\': \'Apple\', \'id\': 380749300, \'id_str\': \'380749300\', \'indices\': [40, 46]}], \'urls\': []}"', 'reply_user_id': 'no', 'reply_status_id': 'no', 'Tweet_Number_of_Likes': 0, 'Tweet_Number_of_Retweets': 2, 'username': '@lowi_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 3, 'stars_score': 0.3213900327682495}, {'created_at': datetime.datetime(2020, 12, 13, 1, 4, 52), 'tweet_id': '1337926427530899458', 'Tweet_Content': "RT @AnaAgp_1967: Estafa d @Lowi_es a trav√©s d SMS autom√°tico ; dice q origina @Apple .\nFactura 42SMS en 1'no enviados.\nContactando con ello‚Ä¶", 'name': 'Raquel Fdez-Veiga', 'user_id': '2439711755', 'user_followers': 8502, 'user_location': 'Barcelona', 'source': 'Twitter for Android', 'entities': '"{\'hashtags\': [], \'symbols\': [], \'user_mentions\': [{\'screen_name\': \'AnaAgp_1967\', \'name\': \'Ana Isabel Gat\\u00f3n\', \'id\': 77646743396 ... (181 characters truncated) ... ': [26, 34]}, {\'screen_name\': \'Apple\', \'name\': \'Apple\', \'id\': 380749300, \'id_str\': \'380749300\', \'indices\': [78, 84]}], \'urls\': []}"', 'reply_user_id': 'no', 'reply_status_id': 'no', 'Tweet_Number_of_Likes': 0, 'Tweet_Number_of_Retweets': 124, 'username': '@lowi_es', 'GRUPO': 'Vodafone', 'urls': 'no url', 'stars': 1, 'stars_score': 0.6548032760620117})
2020-12-15 10:35:32,733 INFO sqlalchemy.engine.base.Engine COMMIT

In [129]:
5+5

10